# YOLOv8 configuration for training with dropout
# File: training.yaml

# Model parameters
nc: 10  # number of classes (Metal, Plastic, Glass, etc.)
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple

# Backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 3, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C2f, [128]],  # 2
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C2f, [256]],  # 4
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 6, C2f, [512]],  # 6
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C2f, [1024]], 
   [-1, 1, MCDropout, [0.1]],  # 8
   [-1, 1, SPPF, [1024, 5]]]  # 9

# Head
head:
  [[-1, 1, nn.Upsample, [None, 2, 'nearest']],  # 10
   [[-1, 6], 1, Concat, [1]],  # 11: cat backbone P4 (6)
   [-1, 3, C2f, [512]],  # 12
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],  # 13
   [[-1, 4], 1, Concat, [1]],  # 14: cat backbone P3 (4)
   [-1, 3, C2f, [256]],  # 15 (P3/8-small)
   [-1, 1, Conv, [256, 3, 2]],  # 16
   [[-1, 12], 1, Concat, [1]],  # 17: cat head P4 (12)
   [-1, 3, C2f, [512]],
   [-1, 1, MCDropout, [0.1]],  # 18
   [-1, 1, Conv, [512, 3, 2]],  # 19
   [[-1, 10], 1, Concat, [1]],  # 20: cat head P5 (9)
   [-1, 3, C2f, [1024]],     # 21 (P5/32-large)
   [-1, 1, MCDropout, [0.1]],  # 22
   [[15, 18, 24], 1, Detect, [nc]]]  # Detect(P3, P4, P5)